version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - 8800:8000
    depends_on:
      - service_master
      - service_slave
  service_master:
    build: ./service_master
    depends_on:
      - logstash
  service_slave:
    build: ./service_slave
    depends_on:
      - logstash
  logstash:
    build: ./logstash
    image: logstash:8.11.1
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
      - "5959:5959"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf 